all

diff --git a/bcm b/bcm
--- a/bcm
+++ b/bcm
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # note the absense of -u allows you to use environment variables from the parent shell
-set -Eeuo pipefail
+set -Eeuox pipefail
 cd "$(dirname "$0")"
 
 # if this is 1, then we assume we are running BCM WITHOUT the front-end (e.g., dockerd on bare metal)
@@ -36,6 +36,18 @@ for i in "$@"; do
     esac
 done
 
+# make sure LXD is installed before we even think of continuing
+if [[ ! -f "$(command -v lxc)" ]]; then
+    echo "ERROR: LXD does not seem to be installed. Please run the BCM installer script."
+    exit
+fi
+
+if lxc info | grep -q "server_clustered: false"; then
+echo "ERROR: The LXD server does not appear to be in the correct state. Please re-run the BCM installer."
+exit
+fi
+
+
 source ./env
 source "$HOME/.bashrc"
 
@@ -49,7 +61,7 @@ export BCM_DEBUG="$BCM_DEBUG"
 export REBUILD_IMAGES="$REBUILD_IMAGES"
 
 BCM_CACHE_DIR=${BCM_CACHE_DIR:-"$HOME/.local/bcm"}
-if [[ ! -z $BCM_CACHE_DIR ]]; then
+if [[ -n $BCM_CACHE_DIR ]]; then
     BCM_CACHE_DIR="$BCM_CACHE_DIR"
 fi
 export BCM_CACHE_DIR="$BCM_CACHE_DIR"
@@ -60,31 +72,31 @@ if [[ -z $ ]]; then
 fi
 
 BCM_SSH_HOSTNAME=${BCM_SSH_HOSTNAME:-"$(hostname)"}
-if [[ ! -z $BCM_SSH_HOSTNAME ]]; then
+if [[ -n $BCM_SSH_HOSTNAME ]]; then
     BCM_SSH_HOSTNAME="$BCM_SSH_HOSTNAME"
 fi
 export BCM_SSH_HOSTNAME="$BCM_SSH_HOSTNAME"
 
 BCM_SSH_USERNAME=${BCM_SSH_USERNAME:-"$(whoami)"}
-if [[ ! -z $BCM_SSH_USERNAME ]]; then
+if [[ -n $BCM_SSH_USERNAME ]]; then
     BCM_SSH_USERNAME="$BCM_SSH_USERNAME"
 fi
 export BCM_SSH_USERNAME="$BCM_SSH_USERNAME"
 
 BCM_ACTIVE_CHAIN=${BCM_ACTIVE_CHAIN:-"testnet"}
-if [[ ! -z $BCM_ACTIVE_CHAIN ]]; then
+if [[ -n $BCM_ACTIVE_CHAIN ]]; then
     BCM_ACTIVE_CHAIN="$BCM_ACTIVE_CHAIN"
 fi
 export BCM_ACTIVE_CHAIN="$BCM_ACTIVE_CHAIN"
 
 GNUPGHOME=${GNUPGHOME:-"$HOME/.gnupg"}
-if [[ ! -z $GNUPGHOME ]]; then
+if [[ -n $GNUPGHOME ]]; then
     GNUPGHOME="$GNUPGHOME"
 fi
 export GNUPGHOME="$GNUPGHOME"
 
 BCM_DATACENTER=${BCM_DATACENTER:-"default"}
-if [[ ! -z $BCM_DATACENTER ]]; then
+if [[ -n $BCM_DATACENTER ]]; then
     BCM_DATACENTER="$BCM_DATACENTER"
 fi
 export BCM_DATACENTER="$BCM_DATACENTER"
@@ -118,9 +130,6 @@ export BCM_STACKS_DIR="$BCM_GIT_DIR/stacks"
 export BASE_DOCKER_IMAGE="ubuntu:20.04"
 export BCM_TMP_DIR="/tmp/bcm" && mkdir -p "$BCM_TMP_DIR"
 
-PASSWDHOME="$HOME/.password-store" && mkdir -p "$PASSWDHOME"
-
-export PASSWDHOME="$PASSWDHOME"
 export LXC_BCM_BASE_IMAGE_NAME="bcm-template"
 
 BCM_MANAGER_HOST_NAME="bcm-manager-01"
